name: ci checks and lint

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    check-typescript:
        name: TypeScript Checks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  cache: npm

            - name: Install Dependencies
              id: npm-ci
              run: npm ci

            - name: Check Format with prettier
              id: npm-format-check
              run: npm run format:check

            - name: Lint with eslint
              id: npm-lint
              run: npm run lint
